export const getWeatherDescription = (code) => {
	const descriptions = {
	  0: 'Céu limpo',
	  1: 'Principalmente limpo',
	  2: 'Parcialmente nublado',
	  3: 'Nublado',
	  45: 'Nevoeiro',
	  48: 'Nevoeiro com geada',
	  51: 'Garoa leve',
	  53: 'Garoa moderada',
	  55: 'Garoa intensa',
	  56: 'Garoa congelante leve',
	  57: 'Garoa congelante intensa',
	  61: 'Chuva leve',
	  63: 'Chuva moderada',
	  65: 'Chuva forte',
	  66: 'Chuva congelante leve',
	  67: 'Chuva congelante forte',
	  71: 'Queda de neve leve',
	  73: 'Queda de neve moderada',
	  75: 'Queda de neve forte',
	  77: 'Grãos de neve',
	  80: 'Pancadas de chuva leves',
	  81: 'Pancadas de chuva moderadas',
	  82: 'Pancadas de chuva violentas',
	  85: 'Pancadas de neve leves',
	  86: 'Pancadas de neve pesadas',
	  95: 'Trovoada leve ou moderada',
	  96: 'Trovoada com granizo leve',
	  99: 'Trovoada com granizo pesado',
	};
	return descriptions[code] || 'Condições desconhecidas';
  };